services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    restart: always
    links:
      - db
    depends_on:
      - db

volumes:
  db_data:

